1926 1927 task aws azure documentation
CGI-FR/IoT-Hub-Portal pull request #1961
Opened 2023-03-27 15:27 UTC by ssgueye2

## Description

What's new?

- #1926 & #1927 => Rework in the documentation

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Tests
- [ ] Other

2023-03-27 16:24 UTC, kbeaugrand requested changes

2023-03-27 16:24 UTC, kbeaugrand commented on docs/aws.md
> +  "AWS:Region": "<AWS_REGION_KEY>"
Please fill here other future settings like : 
- S3 storage connection string

Other settings are also mandatory: 

```
  "OIDC:Scope": "<SCOPE>",
  "OIDC:MetadataUrl": "<METADATA_URL>",
  "OIDC:ClientId": "<CLIENT_ID>",
  "OIDC:Authority": "<AUTHORITY>",
  "OIDC:ApiClientId": "<API_CLIENT_ID>",  
  "PostgreSQL:ConnectionString": "<POSTGRE_SQL_CONNECTION_STRING>"
```

2023-03-28 07:34 UTC, ssgueye2 commented on docs/aws.md
> +  "AWS:Region": "<AWS_REGION_KEY>"
DONE 👍

2023-03-28 07:35 UTC, kbeaugrand approved these changes

2023-03-28 07:35 UTC, merged