Rearrange +
CGI-FR/IoT-Hub-Portal pull request #478
Opened 2022-03-23 15:38 UTC by ChristopheRib63

## Description

What's new?

-#421 Rearrange "+"

## What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

2022-03-24 15:01 UTC, kbeaugrand commented on src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
> +                        <a href="/device-models/new"><MudFab Color="Color.Secondary" Icon="@Icons.Material.Filled.Add" Label="new device-models" id="newDeviceButton" /></a>
Why using an HTML tag instead of the MudIconButton ?

2022-03-24 15:04 UTC, ChristopheRib63 commented
![image](https://user-images.githubusercontent.com/83826573/159877556-5c0ece2d-47b2-4ad8-ba13-6413d45c94ff.png)

Voici les modifications pour un nouvel élément. Votre avis?

2022-03-24 15:21 UTC, ChristopheRib63 commented on src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
> +                    <MudItem xs="0">
Position du  bouton par rapport au rebord de droite

2022-03-24 16:20 UTC, ChristopheRib63 commented
![image](https://user-images.githubusercontent.com/83826573/159962688-1f27abf3-80a9-496b-b254-f8e1c127e07f.png)

2022-03-24 16:21 UTC, ChristopheRib63 commented on src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
> +                        <a href="/device-models/new"><MudFab Color="Color.Secondary" Icon="@Icons.Material.Filled.Add" Label="new device-models" id="newDeviceButton" /></a>
Modified

2022-03-25 06:25 UTC, kbeaugrand requested changes

2022-03-25 06:25 UTC, kbeaugrand commented on src/AzureIoTHub.Portal/Client/Pages/DeviceModels/DeviceModelListPage.razor
> +                           <a href="/device-models/new"><MudFab Color="Color.Secondary" Icon="@Icons.Material.Filled.Add" Size="Size.Medium"  id="newDeviceButton" /></a>
This moves the MudIcon button to a HTML tag.
Why ? is there other options to keep the MudTag instead ? and us the AddDeviceModel Event?

2022-03-25 06:25 UTC, kbeaugrand commented on src/AzureIoTHub.Portal/Client/Pages/Devices/DeviceListPage.razor
> +                 <a href="/devices/new"><MudFab Color="Color.Secondary" Icon="@Icons.Material.Filled.Add" Size="Size.Medium"  id="newDeviceButton" /></a>
Same as previous

2022-03-25 06:25 UTC, kbeaugrand commented on src/AzureIoTHub.Portal/Client/Pages/LoRaWAN/Concentrator/ConcentratorListPage.razor
> +                       <a href="lorawan/concentrators/new"><MudFab Color="Color.Secondary" Icon="@Icons.Material.Filled.Add" Size="Size.Medium"  /></a>
Same as previous

2022-03-25 06:25 UTC, kbeaugrand commented on src/AzureIoTHub.Portal/Client/Pages/Edge_Devices/EdgeDeviceListPage.razor
> +                      <MudFab Color="Color.Secondary" Icon="@Icons.Material.Filled.Add" Size="Size.Medium"  OnClick="ShowAddDialog" />
Here you kept the Mud Tag...

2022-03-26 08:23 UTC, kbeaugrand approved these changes

2022-03-26 08:24 UTC, merged