Deploy portal with and without lorawan
CGI-FR/IoT-Hub-Portal pull request #869
Opened 2022-06-26 21:20 UTC by hocinehacherouf

## Description

What's new?

- Implement #826 

## What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

2022-06-27 15:27 UTC, hocinehacherouf commented on templates/azuredeploy.json
> +        },
Done

2022-06-27 18:21 UTC, kbeaugrand requested changes

2022-06-27 18:21 UTC, kbeaugrand commented on templates/azuredeployUI.json
> +							"type": "Microsoft.Common.TextBox",
Should validate the input : 
- only alpha numeric characters 
- max 16 characters

2022-06-28 06:14 UTC, kbeaugrand commented
Small issue when selecting LoRaWAN feature +not deploy edge device : 

![image](https://user-images.githubusercontent.com/9513635/176106453-4170189d-d7ab-4ca8-9594-ad657ef955f5.png)

2022-06-28 06:16 UTC, kbeaugrand commented
> Small issue when selecting LoRaWAN feature +not deploy edge device :
> 
> ![image](https://user-images.githubusercontent.com/9513635/176106453-4170189d-d7ab-4ca8-9594-ad657ef955f5.png)

Same when not-selecting lorawan : 

![image](https://user-images.githubusercontent.com/9513635/176106671-01494c4d-037b-493e-bad7-a3dc4078cf48.png)

2022-06-28 17:32 UTC, kbeaugrand approved these changes

2022-06-28 17:52 UTC, merged